local opt = vim.opt

opt.smartindent = true
opt.backup = false
opt.completeopt = "menuone,noselect"
opt.encoding= "UTF-8"
opt.expandtab = true
opt.foldenable = false
opt.foldmethod = "manual"
opt.foldnestmax = 1
opt.hidden = true
opt.hlsearch = true
opt.incsearch = true
opt.mouse = "a"
opt.shiftwidth = 2
opt.showmode = false
opt.smartcase = true
opt.softtabstop = 2
opt.splitbelow = true
opt.splitright = true
opt.termguicolors = true
opt.timeoutlen = 500
opt.updatetime = 300
opt.writebackup = false
opt.cursorline = true
opt.number = true
opt.relativenumber = true
opt.signcolumn = "yes"
