return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'kyazdani42/nvim-web-devicons'
  use 'kyazdani42/nvim-tree.lua'
  use 'hoob3rt/lualine.nvim'
  use 'akinsho/nvim-bufferline.lua'
  use 'neovim/nvim-lspconfig'
  use 'terrortylor/nvim-comment'
  use 'nvim-treesitter/nvim-treesitter'
  use 'hrsh7th/nvim-compe'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-telescope/telescope-media-files.nvim'
  use 'nvim-lua/popup.nvim'
  use 'nvim-lua/plenary.nvim'
  use 'norcalli/nvim-colorizer.lua'
  use 'lewis6991/gitsigns.nvim'
  use 'folke/tokyonight.nvim'
  use {'lukas-reineke/indent-blankline.nvim', branch = 'lua'}
  use 'SirVer/ultisnips'
  use 'tpope/vim-surround'
  use 'alvan/vim-closetag'
  use 'dense-analysis/ale'
  use 'jiangmiao/auto-pairs'
end)
