brew "fd"
brew "fzf"
brew "mise"
brew "neovim"
brew "opencode"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "zoxide"

cask "bruno"
cask "dbeaver-community"
cask "google-chrome"
cask "kitty"
cask "maccy"
cask "ngrok"
cask "nikitabobko/tap/aerospace"
cask "obsidian"
cask "orbstack"
cask "tailscale-app"

cask "font-victor-mono"
