return {
  tab_close = "",
  git_add = "│",
  git_change = "│",
  git_delete = "│",
  git_topdelete = "‾",
  git_changedelete = "~",
  git_untracked = "│",
  error = " ",
  warn = " ",
  info = " ",
  hint = " ",
  search = "   ",
  selection = "  ",
  added_outline = " ",
  modified_outline = " ",
  removed_outline = " ",
}
