vim.pack.add({
  "https://github.com/romgrk/barbar.nvim",
  { src = "https://github.com/saghen/blink.cmp", version = vim.version.range("1.*") },
  { src = "https://github.com/catppuccin/nvim", name = "catppuccin" },
  "https://github.com/stevearc/conform.nvim",
  "https://github.com/sindrets/diffview.nvim",
  "https://github.com/j-hui/fidget.nvim",
  "https://github.com/lewis6991/gitsigns.nvim",
  "https://github.com/nvim-lualine/lualine.nvim",
  "https://github.com/mason-org/mason.nvim",
  "https://github.com/nvim-mini/mini.nvim",
  "https://github.com/kylechui/nvim-surround",
  "https://github.com/nvim-treesitter/nvim-treesitter",
  "https://github.com/windwp/nvim-ts-autotag",
  "https://github.com/stevearc/oil.nvim",
  "https://github.com/sphamba/smear-cursor.nvim",
  "https://github.com/folke/snacks.nvim",
  "https://github.com/folke/ts-comments.nvim",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/yioneko/nvim-vtsls",
})
