require('setup')
require('setting')
require('mapping')
require('theme')

require('plugin.ale')
require('plugin.bufferline')
require('plugin.closetag')
require('plugin.colorizer')
require('plugin.comment')
require('plugin.compe')
require('plugin.gitsigns')
require('plugin.indent')
require('plugin.lualine')
require('plugin.tree')
require('plugin.treesitter')
require('plugin.utilsnips')

require('lsp.jsonls')
require('lsp.tsserver')
